### ISSUE TITLE
`multigit` trying to access directory not listed subrepos

### ISSUE THREAD

**Issue by snspinn** [jmnavarrol/simplest-git-subrepos#1]
Firstly, nicely done on this. 
When running `multigit --list|--clone`, the scripts trying to read directories not listed in the subrepos file.

Example subrepos
```
declare -A REPOS
REPOS["level_1/level_2/sub1"]="https://git.sub1.git" 
REPOS["level_1/level_2/sub2"]="https://git.sub2.git"
```

directory structure
```
~/toplevel_git
|_______ level_1/level_2/
                |______ sub1
                |______ sub1
                |______ other_directory
```

Output from `multigit --list`
```
find: ‘./level_1/level_2/other_directory/data/postgres’: Permission denied
./level_1/level_2/sub2 defined as clone of: https://git.sub1.git
./level_1/level_2/sub1 defined as clone of: https://git.sub2.git
```

The reason for the permission denied is known. My question is, does multigit scan through all possibilities within the highest level directory know to it, i.e. `level_1`?
I don't mind these errors but except that I wouldn't want to script trying running commands in directories I don't intend it to, such as a git repo I am "trying out" in the workflow but don't have all my versioning & branching sorted properly.

**Comment by jmnavarrol** [comment]
Thanks for your feedback.

Didn't look at the sources yet; I'll review.

Nevertheless, you should know this script is merely conceived to illustrate the subrepos' concept (just add them to your .gitignore and then you could manage your directory tree as if they are isolated sandboxes) and thus don't expect new features or any way going beyond what it is now (but I'll ceratainly consider bugs).

For an implementation meant to be "production-grade", please review its Python version at https://github.com/jmnavarrol/python-multigit, moreso when in combination with BME (https://github.com/jmnavarrol/bash-magic-enviro).

**Comment by jmnavarrol** [comment]
> The reason for the permission denied is known. My question is, does multigit scan through all possibilities within the highest level directory know to it, i.e. `level_1`? I don't mind these errors but except that I wouldn't want to script trying running commands in directories I don't intend it to, such as a git repo I am "trying out" in the workflow but don't have all my versioning & branching sorted properly.

As per documentation, operations are recursive starting in current dir, i.e. $PWD.  The script uses find to look for files named *"subrepos"* within the current directory tree (hence your *"Permision denied"* error).  On actionable operations (clone, checkout) the script also runs find again on each declared subrepo entry, in case new *"subrepos"* files were downloaded and so on.

I hope this answers your question.

> I don't mind these errors but except that I wouldn't want to script trying running commands in directories I don't intend it to, such as a git repo I am "trying out" in the workflow but don't have all my versioning & branching sorted properly.

This bugged me enough to updated this project's [README](../#readme) with a big warning early on the file, so thank you for making me think of that.

I don't think there's anything more I should do about this, so I'm going to close it here.  Nevertheless, feel free to add further info, reply, etc. if you deem it proper.

Best regards.

**Comment by jmnavarrol** [comment]
Closed.
